DROP TABLE IF EXISTS site_material;
DROP TABLE IF EXISTS bilan;
DROP TABLE IF EXISTS material;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS site;
DROP TABLE IF EXISTS society;

CREATE TABLE society (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail VARCHAR(256) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    society_id BIGINT NOT NULL,
    CONSTRAINT fk_app_user_society FOREIGN KEY (society_id) REFERENCES society(id)
);

CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    number_employee INTEGER NOT NULL,
    parking_places INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    number_pc INTEGER NOT NULL,
    society_id BIGINT NOT NULL,
    CONSTRAINT fk_site_society FOREIGN KEY (society_id) REFERENCES society(id)
);

CREATE TABLE material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    energetic_value DOUBLE NOT NULL,
    quantity DOUBLE NOT NULL
);

CREATE TABLE site_material (
    site_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    PRIMARY KEY (site_id, material_id),
    CONSTRAINT fk_site_material_site FOREIGN KEY (site_id) REFERENCES site(id),
    CONSTRAINT fk_site_material_material FOREIGN KEY (material_id) REFERENCES material(id)
);

CREATE TABLE bilan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    electricity_kwh_year DOUBLE NOT NULL,
    gas_kwh_year DOUBLE NOT NULL,
    total_co2 DOUBLE NOT NULL,
    calculation_date DATE NOT NULL,
    site_id BIGINT NOT NULL,
    CONSTRAINT fk_bilan_site FOREIGN KEY (site_id) REFERENCES site(id)
);
